services:
  patchdoc:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /volume1/docker/patchbook/data:/data
      - /volume1/docker/patchbook/public:/app/public
    restart: unless-stopped
    env_file:
      - .env
